### ISSUE TITLE
Simultaneous RX/TX ?

### ISSUE THREAD

**Issue by Buanderie** [StevenMHernandez/ESP32-CSI-Tool#15]
That might sound like a silly question, but...
Would it be possible to send (or inject) packets from one board, and receive CSI data from the same board at the same time ? (receiving its own packets) ?

**Comment by StevenMHernandez** [comment]
Sorry, but I do not think that would be possible. The time it takes to transmit would overlap with the time it would need to receive the signal.

Don't worry about asking silly questions. :)
