### ISSUE TITLE
Error while Flashing ESP32

### ISSUE THREAD

**Issue by arcgolatkar** [StevenMHernandez/ESP32-CSI-Tool#20]
I am getting the following error while flashing the ESP32. (shown in img)
I have followed the readme for the menuconfig and have ESP-IDF v4.1. 
Working on a single ESP in station mode and moble's hotspot as AP.  I have changed 'myssid' and 'mypassword' to the mobile hotspot ssid and pwd. Wondering if doing this can connect my ESP to the hotspot ?.
![Screenshot from 2021-07-08 15-20-39](https://user-images.githubusercontent.com/47918300/124902324-73104500-e000-11eb-9194-8d09728fcf47.png)

**Comment by StevenMHernandez** [comment]
"A fatal error occurred: Timed out waiting for packet header"


Do you need to hold a "flash" button to flash this ESP32?

**Comment by arcgolatkar** [comment]
Yes

**Comment by StevenMHernandez** [comment]
Is the issue resolved? Can I close this issue?
