### ISSUE TITLE
Active_ap mode: CSI collection process not smooth

### ISSUE THREAD

**Issue by tusharjain1003** [StevenMHernandez/ESP32-CSI-Tool#30]
In active_ap mode, the CSI collection process is not smooth and gets stuck randomly.

- Baud Rate: 1552000 
- WiFi Channel per Device: 6
- FreeRTOS > Tick rate (Hz): 1000

1. Build project(s) `...` active_ap 
2. Flash project(s) `...` active_ap
3. External device setup (if applicable)
3. See error

 - OS: Windows
 - ESP-IDF Version: 4.0
 
using smartphone as sta.

**Comment by StevenMHernandez** [comment]
At what rate do yuo have the smartphone sending CSI frames? If you are not controlling the data output by the smartphone, then it is likely the smartphone is not sending any frames OR the frames being sent do not generate CSI.

**Comment by kallu1294** [comment]
> At what rate do yuo have the smartphone sending CSI frames? If you are not controlling the data output by the smartphone, then it is likely the smartphone is not sending any frames OR the frames being sent do not generate CSI.

Sir can we make our smartphone as STA and  esp32 as AP.? Are we able to see CSI frames.??

**Comment by StevenMHernandez** [comment]
@kallu1294 Yes this is possible. However, I cannot guarantee consistent CSI frame-rate. This is an **advanced** usage of this ESP-CSI-Tool and I cannot promise that I will be able to debug any issues from "non-supported hardware" like smartphones. If you have advanced understanding of what is going on, you should be able to identify methods to get this working. I just do not know how much engineering effort would be required.

**Comment by kallu1294** [comment]
Sir for this then I can't use my smartphone or wifi (router) as AP .?

So I should use two esp32 one for AP and another one for STA right.??

**Comment by StevenMHernandez** [comment]
Two esp32s is the **recommended** way with this tool. Yes.

It is possible to use a smartphone or an AP, but you will need advanced knowledge.

**Comment by kallu1294** [comment]
Ok thank you sir for the reply

What if I make esp32 as STA and my wifi router as AP will I'm able to
capture CSI data..??

However CSI is coming but I'm not able to download those data

Is there any solution for this.??

**Comment by StevenMHernandez** [comment]
Yes, that should work too. 

@kallu1294, I have already answered this question for you in the other thread 12 hours ago (#44) and in a different thread 9 days ago (#45). 

At this point I am afraid that you are not being respectful of my help and my time. It also seems like you are not trying to debug these issues yourself.

**Comment by kallu1294** [comment]
I'm trying sir 😕 CSV file is getting created but It is empty

**Comment by kallu1294** [comment]
In #44 serial port was an issue that was solved and at the end I mentioned
that too csv file is empty 😕

**Comment by kallu1294** [comment]
> Yes, that should work too.
> 
> @kallu1294, I have already answered this question for you in the other thread 12 hours ago (#44) and in a different thread 9 days ago (#45).
> 
> At this point I am afraid that you are not being respectful of my help and my time. It also seems like you are not trying to debug these issues yourself.


literally sorry sir but I'm trying my best to figure it out, CSV file getting created but it is empty

**Comment by StevenMHernandez** [comment]
Closing old issues.
