### ISSUE TITLE
Unicode decode error with the python utility, and weird logs in terminal

### ISSUE THREAD

**Issue by yc541** [StevenMHernandez/ESP32-CSI-Tool#35]
Hello!

I am using a PC with Ubuntu 20.04, ESP-IDF 4.0 and NodeMCU kit. 

There are some unicode decode errors when I try to use the python utility to include timestamps (see attached). There is another NodeMCN running the AP application connected to the same PC at /dev/ttyUSB1
![Screenshot from 2021-09-14 13-59-12](https://user-images.githubusercontent.com/8125847/133263835-919c1448-55ff-421c-9b6b-e8f04cbbee03.png)
There is a my-experiment-file-sta.csv created but it is empty. 

Also when I just run idf.py monitor without using the python utility, there are some incorrectly decoded logs in the terminal. 

Here are my outputs of locale
![Screenshot from 2021-09-14 13-59-40](https://user-images.githubusercontent.com/8125847/133264760-9073c99e-b8bf-40af-a6a4-b66a0be117e1.png)

Any help would be appreciated!

**Update:** 
Just did the same on an old laptop with Ubuntu 18.04, the terminal logs are correctly decoded and the python utility is working. The STA application (when using the python utility) is not responding to Ctrl+], but Ctrl+C quits it. 

I'm not sure what's going on with the first PC, but I would like to get it to work so the two ESP32 chips can be physically separated to collect data.

**Comment by StevenMHernandez** [comment]
This looks indicative of an incorrect serial baud rate can you double and triple check that the baud rate you set for the ubuntu 20.04 machine is correct

**Comment by yc541** [comment]
@StevenMHernandez,

Thanks for this! 
I just checked both baud rate are set at 1552000 on the 20.04 machine (the 18.04 machine has the same baud rate). I tried 1152000 on the 20.04 machine as well but the result is the same.

![Screenshot from 2021-09-16 14-02-38](https://user-images.githubusercontent.com/8125847/133617450-b4b49ef7-142f-46fc-a58f-6069b3a51e95.png)
![Screenshot from 2021-09-16 14-03-25](https://user-images.githubusercontent.com/8125847/133617458-bdb86cb1-1592-4188-8946-e87e8589e085.png)

**Comment by StevenMHernandez** [comment]
> "It is important that you are able to successfully build and flash the example project from the esp-idf guide onto your own esp32."

I need you to try the above.

You need to figure out if it is a problem with the esp32-csi-tool or more likely an external problem (faulty computer hardware/issues with your installed ESP32-IDF/operating system issue/etc.)

Please run one of the example projects from the esp-idf guide (try using the low baud rates and high baud rates). If you are not able to get those working, than it is probably not an issue with this project specifically.

**Comment by yc541** [comment]
@StevenMHernandez 

Thanks for the advice! 

I run the example hello world with default 115200 baudrate, it works, but with 1552000 baudrate (the 18.04 machine runs OK with this baudrate) I see similar garbled logs. So I try to reduce the baudrate and it seems that the maximum baudrate I can get is 921600 on the 20.04 machine. Both station and ap run OK with this baudrate. However I'm still getting the unicode error when using the python utility, I will try testing it on a third machine, this seems to be a machine specific issue.

**Comment by StevenMHernandez** [comment]
I believe this problem was solved by changing the baud rates. In which case, issue #5 is related.

I will close this for now. Feel free to reopen if the issues were not solved.
