### ISSUE TITLE
When exporting CSI：BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by YXW-123** [StevenMHernandez/ESP32-CSI-Tool#40]
**Describe the bug**
When using the command：idf.py -p /dev/ttyUSB0 monitor | grep "CSI_DATA" > my-experiment-file.csv ,there is a error:BrokenPipeError: [Errno 32] Broken pipe

**Tool Settings**
- Baud Rate: [1152000]  (using a lower baud rate *WILL* cause issues. **this is the most common issue**)
- WiFi Channel per Device: [ 6]
- FreeRTOS > Tick rate (Hz): [1000]

**To Reproduce**
1. cd ./active_ap
2. Recording to the README.md use the commond: idf.py menuconfig
3. idf.py -p /dev/ttyUSB0 flash
4. use the commond :idf.py -p /dev/ttyUSB0 monitor ,then let my phone connect to the AP,it can collect CSI successfully.
![QQ图片20211112105551](https://user-images.githubusercontent.com/76991913/141402093-185958a5-a751-4f38-8654-92737be90df1.png)

5. use the commond:idf.py -p /dev/ttyUSB0 monitor | grep "CSI_DATA" > my-experiment-file.csv , let my phone connect to the AP, then it printed the error like this :
![QQ图片20211112105720](https://user-images.githubusercontent.com/76991913/141401767-e3c427e1-3f6b-47b6-89d5-0cd1db73f169.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu16.04]
 - ESP-IDF Version: [4.2.1]

**Comment by StevenMHernandez** [comment]
Try each of these and report the results:

- `idf.py -p /dev/ttyUSB0 monitor`
- `idf.py -p /dev/ttyUSB0 monitor | grep "CSI_DATA"`
- `idf.py -p /dev/ttyUSB0 monitor | grep "CSI_DATA" > my-experiment-file.csv`

Which one causes the error?

Did you try to monitor the ESP32 from multiple terminals at the same time?

**Comment by YXW-123** [comment]
> Try each of these and report the results:
> 
> 1. `idf.py -p /dev/ttyUSB0 monitor`
![QQ图片20211112105551](https://user-images.githubusercontent.com/76991913/141410134-1ca1b2e4-6462-473f-b7a3-902d9c5b0403.png)

> 2. `idf.py -p /dev/ttyUSB0 monitor | grep "CSI_DATA"`
![QQ图片20211112123648](https://user-images.githubusercontent.com/76991913/141411111-79ad4924-24b2-4991-bcd8-d230726a0f6d.png)

> 3. `idf.py -p /dev/ttyUSB0 monitor | grep "CSI_DATA" > my-experiment-file.csv`
> 
![QQ图片20211112105720](https://user-images.githubusercontent.com/76991913/141411123-4945e304-bd68-4291-b695-2c2b8afa3c6b.png)

> Which one causes the error?
> The 2nd and 3rd

> I used a  terminal for AP and another terminal for sta.But when I only open a terminal for AP,the commond 2nd or 3rd still causes same error.

**Comment by StevenMHernandez** [comment]
This ultimately looks like an issue with the esp-idf (not my project). Can you try flashing one of the esp-idf example projects and run `idf.py -p /dev/ttyUSB0 monitor | grep "CSI_DATA"`.

Piping data is a normal task in linux, I am not sure why this would be happening to you. I have found (https://github.com/pyserial/pyserial/issues/139) which has some information on broken pipes with esp-idf, however I am not sure that it will help you. What steps have you taken so far to debug this or to find solutions on the internet?

**Comment by YXW-123** [comment]
> This ultimately looks like an issue with the esp-idf (not my project). Can you try flashing one of the esp-idf example projects and run `idf.py -p /dev/ttyUSB0 monitor | grep "CSI_DATA"`.
> 
> Piping data is a normal task in linux, I am not sure why this would be happening to you. I have found ([pyserial/pyserial#139](https://github.com/pyserial/pyserial/issues/139)) which has some information on broken pipes, however I am not sure that it will help you. What steps have you taken so far to debug this or to find solutions on the internet?

Thanks for your help! 
***Firstly,I have added some code like this to miniterm.py:
import sys

try:
   ******************
except (BrokenPipeError, IOError):
    pass

sys.stderr.close()

 I found it  didn't report error ，but it couldn't exporting data either.
***Secondly,I try to use the ESP-IDF v4.3.0,when generate bin，it reported error:
panda@panda-virtual-machine:~/ESP32-CSI-Tool-master/active_ap$  idf.py build

Executing action: all (aliases: build)
Running ninja in directory /home/panda/ESP32-CSI-Tool-master/active_ap/build
Executing "ninja all"...
[2/9] Performing build step for 'bootloader'
ninja: no work to do.
[2/7] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/main.cc.obj
FAILED: /home/panda/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++   -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I/home/panda/esp/esp-idf/components/newlib/platform_include -I/home/panda/esp/esp-idf/components/freertos/include -I/home/panda/esp/esp-idf/components/freertos/port/xtensa/include -I/home/panda/esp/esp-idf/components/esp_hw_support/include -I/home/panda/esp/esp-idf/components/esp_hw_support/port/esp32/. -I/home/panda/esp/esp-idf/components/heap/include -I/home/panda/esp/esp-idf/components/log/include -I/home/panda/esp/esp-idf/components/lwip/include/apps -I/home/panda/esp/esp-idf/components/lwip/include/apps/sntp -I/home/panda/esp/esp-idf/components/lwip/lwip/src/include -I/home/panda/esp/esp-idf/components/lwip/port/esp32/include -I/home/panda/esp/esp-idf/components/lwip/port/esp32/include/arch -I/home/panda/esp/esp-idf/components/soc/include -I/home/panda/esp/esp-idf/components/soc/esp32/. -I/home/panda/esp/esp-idf/components/soc/esp32/include -I/home/panda/esp/esp-idf/components/hal/esp32/include -I/home/panda/esp/esp-idf/components/hal/include -I/home/panda/esp/esp-idf/components/esp_rom/include -I/home/panda/esp/esp-idf/components/esp_rom/esp32 -I/home/panda/esp/esp-idf/components/esp_rom/include/esp32 -I/home/panda/esp/esp-idf/components/esp_common/include -I/home/panda/esp/esp-idf/components/esp_system/include -I/home/panda/esp/esp-idf/components/esp32/include -I/home/panda/esp/esp-idf/components/driver/include -I/home/panda/esp/esp-idf/components/driver/esp32/include -I/home/panda/esp/esp-idf/components/esp_ringbuf/include -I/home/panda/esp/esp-idf/components/efuse/include -I/home/panda/esp/esp-idf/components/efuse/esp32/include -I/home/panda/esp/esp-idf/components/xtensa/include -I/home/panda/esp/esp-idf/components/xtensa/esp32/include -I/home/panda/esp/esp-idf/components/espcoredump/include -I/home/panda/esp/esp-idf/components/esp_timer/include -I/home/panda/esp/esp-idf/components/esp_ipc/include -I/home/panda/esp/esp-idf/components/esp_pm/include -I/home/panda/esp/esp-idf/components/vfs/include -I/home/panda/esp/esp-idf/components/esp_wifi/include -I/home/panda/esp/esp-idf/components/esp_wifi/esp32/include -I/home/panda/esp/esp-idf/components/esp_event/include -I/home/panda/esp/esp-idf/components/esp_netif/include -I/home/panda/esp/esp-idf/components/esp_eth/include -I/home/panda/esp/esp-idf/components/tcpip_adapter/include -I/home/panda/esp/esp-idf/components/app_trace/include -I/home/panda/esp/esp-idf/components/mbedtls/port/include -I/home/panda/esp/esp-idf/components/mbedtls/mbedtls/include -I/home/panda/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -I/home/panda/esp/esp-idf/components/app_update/include -I/home/panda/esp/esp-idf/components/spi_flash/include -I/home/panda/esp/esp-idf/components/bootloader_support/include -I/home/panda/esp/esp-idf/components/nvs_flash/include -I/home/panda/esp/esp-idf/components/pthread/include -I/home/panda/esp/esp-idf/components/esp_gdbstub/include -I/home/panda/esp/esp-idf/components/esp_gdbstub/xtensa -I/home/panda/esp/esp-idf/components/esp_gdbstub/esp32 -I/home/panda/esp/esp-idf/components/perfmon/include -I/home/panda/esp/esp-idf/components/wpa_supplicant/include -I/home/panda/esp/esp-idf/components/wpa_supplicant/port/include -I/home/panda/esp/esp-idf/components/wpa_supplicant/include/esp_supplicant -I/home/panda/esp/esp-idf/components/protobuf-c/protobuf-c -I/home/panda/esp/esp-idf/components/wear_levelling/include -I/home/panda/esp/esp-idf/components/sdmmc/include -I/home/panda/esp/esp-idf/components/fatfs/diskio -I/home/panda/esp/esp-idf/components/fatfs/vfs -I/home/panda/esp/esp-idf/components/fatfs/src -I/home/panda/esp/esp-idf/components/esp_adc_cal/include -I/home/panda/esp/esp-idf/components/nghttp/port/include -I/home/panda/esp/esp-idf/components/nghttp/nghttp2/lib/includes -I/home/panda/esp/esp-idf/components/esp-tls -I/home/panda/esp/esp-idf/components/esp-tls/esp-tls-crypto -I/home/panda/esp/esp-idf/components/tcp_transport/include -I/home/panda/esp/esp-idf/components/esp_websocket_client/include -I/home/panda/esp/esp-idf/components/spiffs/include -I/home/panda/esp/esp-idf/components/esp_http_client/include -I/home/panda/esp/esp-idf/components/libsodium/libsodium/src/libsodium/include -I/home/panda/esp/esp-idf/components/libsodium/port_include -I/home/panda/esp/esp-idf/components/json/cJSON -I/home/panda/esp/esp-idf/components/unity/include -I/home/panda/esp/esp-idf/components/unity/unity/src -I/home/panda/esp/esp-idf/components/cbor/port/include -I/home/panda/esp/esp-idf/components/ulp/include -I/home/panda/esp/esp-idf/components/openssl/include -I/home/panda/esp/esp-idf/components/console -I/home/panda/esp/esp-idf/components/esp_http_server/include -I/home/panda/esp/esp-idf/components/protocomm/include/common -I/home/panda/esp/esp-idf/components/protocomm/include/security -I/home/panda/esp/esp-idf/components/protocomm/include/transports -I/home/panda/esp/esp-idf/components/mdns/include -I/home/panda/esp/esp-idf/components/wifi_provisioning/include -I/home/panda/esp/esp-idf/components/mqtt/esp-mqtt/include -I/home/panda/esp/esp-idf/components/esp_local_ctrl/include -I/home/panda/esp/esp-idf/components/esp_https_ota/include -I/home/panda/esp/esp-idf/components/esp_hid/include -I/home/panda/esp/esp-idf/components/asio/asio/asio/include -I/home/panda/esp/esp-idf/components/asio/port/include -I/home/panda/esp/esp-idf/components/jsmn/include -I/home/panda/esp/esp-idf/components/expat/expat/expat/lib -I/home/panda/esp/esp-idf/components/expat/port/include -I/home/panda/esp/esp-idf/components/cmock/CMock/src -I/home/panda/esp/esp-idf/components/freemodbus/common/include -I/home/panda/esp/esp-idf/components/esp_serial_slave_link/include -I/home/panda/esp/esp-idf/components/idf_test/include -I/home/panda/esp/esp-idf/components/idf_test/include/esp32 -I/home/panda/esp/esp-idf/components/coap/port/include -I/home/panda/esp/esp-idf/components/coap/port/include/coap -I/home/panda/esp/esp-idf/components/coap/libcoap/include -I/home/panda/esp/esp-idf/components/coap/libcoap/include/coap2 -mlongcalls -Wno-frame-address   -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -std=gnu++11 -fno-exceptions -fno-rtti -D_GNU_SOURCE -DIDF_VER=\"v4.3.1\" -DESP_PLATFORM -MMD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.cc.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/main.cc.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.cc.obj -c ../main/main.cc
In file included from ../main/main.cc:8:
/home/panda/esp/esp-idf/components/esp_event/include/esp_event_loop.h:2:2: warning: #warning "esp_event_loop.h is deprecated, please include esp_event.h instead" [-Wcpp]
 #warning "esp_event_loop.h is deprecated, please include esp_event.h instead"
  ^~~~~~~
../main/main.cc: In function 'void softap_init()':
../main/main.cc:93:24: warning: 'void tcpip_adapter_init()' is deprecated [-Wdeprecated-declarations]
     tcpip_adapter_init();
                        ^
In file included from /home/panda/esp/esp-idf/components/esp_netif/include/esp_netif.h:35,
                 from /home/panda/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:22,
                 from /home/panda/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /home/panda/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:64,
                 from ../main/main.cc:7:
/home/panda/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:34:6: note: declared here
 void tcpip_adapter_init(void)  __attribute__ ((deprecated));
      ^~~~~~~~~~~~~~~~~~
../main/main.cc:93:24: warning: 'void tcpip_adapter_init()' is deprecated [-Wdeprecated-declarations]
     tcpip_adapter_init();
                        ^
In file included from /home/panda/esp/esp-idf/components/esp_netif/include/esp_netif.h:35,
                 from /home/panda/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:22,
                 from /home/panda/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /home/panda/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:64,
                 from ../main/main.cc:7:
/home/panda/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:34:6: note: declared here
 void tcpip_adapter_init(void)  __attribute__ ((deprecated));
      ^~~~~~~~~~~~~~~~~~
In file included from /home/panda/esp/esp-idf/components/esp_timer/include/esp_timer.h:45,
                 from /home/panda/esp/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:46,
                 from /home/panda/esp/esp-idf/components/freertos/include/freertos/portable.h:52,
                 from /home/panda/esp/esp-idf/components/freertos/include/freertos/FreeRTOS.h:64,
                 from ../main/main.cc:2:
../main/main.cc:95:60: warning: 'esp_err_t esp_event_loop_init(system_event_cb_t, void*)' is deprecated [-Wdeprecated-declarations]
     ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL));
                                                            ^
/home/panda/esp/esp-idf/components/esp_common/include/esp_err.h:119:31: note: in definition of macro 'ESP_ERROR_CHECK'
         esp_err_t __err_rc = (x);                                       \
                               ^
In file included from /home/panda/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /home/panda/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:64,
                 from ../main/main.cc:7:
/home/panda/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:240:11: note: declared here
 esp_err_t esp_event_loop_init(system_event_cb_t cb, void *ctx) __attribute__ ((deprecated));
           ^~~~~~~~~~~~~~~~~~~
In file included from /home/panda/esp/esp-idf/components/esp_timer/include/esp_timer.h:45,
                 from /home/panda/esp/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:46,
                 from /home/panda/esp/esp-idf/components/freertos/include/freertos/portable.h:52,
                 from /home/panda/esp/esp-idf/components/freertos/include/freertos/FreeRTOS.h:64,
                 from ../main/main.cc:2:
../main/main.cc:95:60: warning: 'esp_err_t esp_event_loop_init(system_event_cb_t, void*)' is deprecated [-Wdeprecated-declarations]
     ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL));
                                                            ^
/home/panda/esp/esp-idf/components/esp_common/include/esp_err.h:119:31: note: in definition of macro 'ESP_ERROR_CHECK'
         esp_err_t __err_rc = (x);                                       \
                               ^
In file included from /home/panda/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /home/panda/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:64,
                 from ../main/main.cc:7:
/home/panda/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:240:11: note: declared here
 esp_err_t esp_event_loop_init(system_event_cb_t cb, void *ctx) __attribute__ ((deprecated));
           ^~~~~~~~~~~~~~~~~~~
../main/main.cc:105:5: warning: missing initializer for member 'wifi_ap_config_t::ssid' [-Wmissing-field-initializers]
     };
     ^
../main/main.cc:105:5: warning: missing initializer for member 'wifi_ap_config_t::password' [-Wmissing-field-initializers]
../main/main.cc:105:5: warning: missing initializer for member 'wifi_ap_config_t::ssid_len' [-Wmissing-field-initializers]
../main/main.cc:105:5: warning: missing initializer for member 'wifi_ap_config_t::ssid_hidden' [-Wmissing-field-initializers]
../main/main.cc:105:5: warning: missing initializer for member 'wifi_ap_config_t::beacon_interval' [-Wmissing-field-initializers]
../main/main.cc:105:5: warning: missing initializer for member 'wifi_ap_config_t::pairwise_cipher' [-Wmissing-field-initializers]
../main/main.cc:105:5: warning: missing initializer for member 'wifi_ap_config_t::ftm_responder' [-Wmissing-field-initializers]
In file included from /home/panda/esp/esp-idf/components/esp_timer/include/esp_timer.h:45,
                 from /home/panda/esp/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:46,
                 from /home/panda/esp/esp-idf/components/freertos/include/freertos/portable.h:52,
                 from /home/panda/esp/esp-idf/components/freertos/include/freertos/FreeRTOS.h:64,
                 from ../main/main.cc:2:
../main/main.cc:115:69: error: cannot convert 'esp_interface_t' to 'wifi_interface_t'
     ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_AP, &wifi_config));
                                                                     ^
/home/panda/esp/esp-idf/components/esp_common/include/esp_err.h:119:31: note: in definition of macro 'ESP_ERROR_CHECK'
         esp_err_t __err_rc = (x);                                       \
                               ^
In file included from ../main/main.cc:7:
/home/panda/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:800:48: note:   initializing argument 1 of 'esp_err_t esp_wifi_set_config(wifi_interface_t, wifi_config_t*)'
 esp_err_t esp_wifi_set_config(wifi_interface_t interface, wifi_config_t *conf);
                               ~~~~~~~~~~~~~~~~~^~~~~~~~~
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by StevenMHernandez** [comment]
#37 deals with issues with esp-idf 4.3

Please review the thread. It will tell you how you can get rid of this issue in v4.3

**Comment by StevenMHernandez** [comment]
This project is now using esp-idf v4.3 which should have solved this issue. If the problem still persists, please reopen the issue and let me know. Thanks.

**Comment by YXW-123** [comment]
Thanks for your advice.I have tried to using esp-idf(release v.4.3.1),but the problem still persists.
![4 3失败](https://user-images.githubusercontent.com/76991913/148678287-e30ed229-705b-4b29-891c-88200c0dc1fc.png)

**Comment by YXW-123** [comment]
Thanks fo your advice .I solved this problem through the following steps：
1.OS: change [Ubuntu16.04] to 20.04 ( the python version changed from 3.7 to 3.8,I guess it has something to do with this)
2.ESP-IDF Version: change [4.2.1] to 4.3
3.Using the latest project you provided 
4.Run command`idf.py monitor | grep "CSI_DATA" > my-experiment-file.csv `，it can work correctly.
5.Run command `idf.py monitor | python ./python_utils/serial_append_time.py > my-experiment-file.csv`,[Errno 32]Broken pipe again,and it prompts that the file or directory ' ./python_utils/serial_append_time.py 'cannot be found.
6. Change the commond to `idf.py monitor | python ../python_utils/serial_append_time.py > my-experiment-file.csv`,it can work correctly.

**Comment by StevenMHernandez** [comment]
Does this mean your issue has been resolved? Can I close the issue?

**Comment by YXW-123** [comment]
Yes!
