### ISSUE TITLE
accessing issue

### ISSUE THREAD

**Issue by kallu1294** [StevenMHernandez/ESP32-CSI-Tool#42]

**Comment by kallu1294** [comment]
why i can not able to access the settings which you are mentioned for starting..??

**Comment by StevenMHernandez** [comment]
You need to provide more information. Specifically, you need to mention the "steps to reproduce" and other information such as "OS", "ESP-IDF", "ESP32-CSI-Tool Git Hash". 

Please edit the original issue message with relevant information. 

Let me know when you have edited the information. The more _useful_ information that you give, the easier it will be to help you.
