### ISSUE TITLE
Monitor garbled

### ISSUE THREAD

**Issue by YXW-123** [StevenMHernandez/ESP32-CSI-Tool#50]
**Describe the bug**
After flashing this tool, it displays garbled characters rather than CSI data when running.

**Tool Settings**
- Baud Rate: [1152000] 
- WiFi Channel per Device: [6]
- FreeRTOS > Tick rate (Hz): [1000]

**To Reproduce**
1. Build project(s) `active_ap` 
2. Flash and monitor project(s) active_ap
3. See error like this 
![2022-01-22 21-22-49 的屏幕截图](https://user-images.githubusercontent.com/76991913/150640488-84277c58-ff3d-47bd-ac4d-fe1ed2335e7c.jpg)

**Desktop (please complete the following information):**
 - OS: [ Ubuntu20.04]
 - ESP-IDF Version: [4.3]
 - ESP32-CSI-Tool Git Hash: []Sorry for not knowing how to get this value

**Remark**
There is no error when starting with get-started/hello_world project from examples directory in IDF.

**Comment by StevenMHernandez** [comment]
Thank you for checking to see if `get-started/hello_world` works.

Please make sure to follow all of the 7 steps in https://github.com/StevenMHernandez/ESP32-CSI-Tool#configuration-esp-idf. The new version of ESP-IDF v4.3 requires a few extra steps that you might not have done previously when you were using older versions of the ESP-IDF.

Can you confirm that you set all of the 'UART' and 'baud rate' related configuration values correctly?

**Comment by YXW-123** [comment]
Sorry I forgot to write clearly to complete the configuration step, I can make sure set all of the 'UART' and 'baud rate' related configuration values correctly. I try to flash and monitor again, but there is the same error.

**Comment by YXW-123** [comment]
Thanks for your help! After looking up some information，I find that garbled phenomenon is related to 'baud rate' .Now I use a much lower value(115200) ,this tool can  run correctly!

**Comment by StevenMHernandez** [comment]
I am glad this worked for you. I will close the issue.
