### ISSUE TITLE
sample rate of CSI

### ISSUE THREAD

**Issue by zhy102** [StevenMHernandez/ESP32-CSI-Tool#55]
Get how to set the sample rate of CSI, for example, set 100hz to collect 100 packets a second. Also, is there any way to set up automatic collection of CSI data for a period of time to avoid interference from people in the environment?

**Comment by StevenMHernandez** [comment]
I do not understand the question. You labelled this as a bug. Is that correct?

You can change the sampling rate by running `idf.py menuconfig` in the `active_sta` project (NOT the `active_ap` project!).

**Comment by StevenMHernandez** [comment]
Closing old issues.

**Comment by mtijan** [comment]
i've question, how to set up 100Hz or another number to collect 100 packet  a second ? @StevenMHernandez @zhy102
