### ISSUE TITLE
the code for drawing

### ISSUE THREAD

**Issue by gmcd310** [StevenMHernandez/ESP32-CSI-Tool#57]
Dear StevenMHernandez, I can collect CSI data now. I need the code for drawing or real-time visualization of data. I hope to get your help.

**Comment by StevenMHernandez** [comment]
See #24

**Comment by gmcd310** [comment]
I tried to visualize CSI data, but I am not able to plot real time data. Can you please send a copy of the code which you have done.

**Comment by StevenMHernandez** [comment]
Did you have specific errors? I would suggest that you ask in the other github-issue since other people have participated previously.
