### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ZaQa92** [StevenMHernandez/ESP32-CSI-Tool#63]
Hi
I've been working on a project related to wifi-sensing and we're going to use esp32 in our project. As I've read articles so far, the CSI matrix should be a vector of complex numbers. I am wondering why the output of this toolkit on CSI only includes some real numbers? Where are the imaginaries? How can I calculate the amplitude and phase of the subcarriers?
I would be grateful if someone could explain it to me.

**Comment by ThomasBouiniere** [comment]
Hello, I have the same question, do you have the answer ?

**Comment by StevenMHernandez** [comment]
See: https://github.com/StevenMHernandez/ESP32-CSI-Tool/blob/master/python_utils/parse_csi.py
