### ISSUE TITLE
Raw CSI data

### ISSUE THREAD

**Issue by tiyuuu** [StevenMHernandez/ESP32-CSI-Tool#64]
I want help regarding how to preprocess raw CSI data to remove noise and for further use. What will be the further steps?

I am using ESP32,python and OS windows

**Comment by StevenMHernandez** [comment]
Unfortunately I cannot help with specific coding questions in the project. It is dependent on your problem.

However, please take a look at one of our latest papers titled: ["WiFi Sensing on the Edge: Signal Processing Techniques and Challenges for Real-World Systems"](https://www.people.vcu.edu/~ebulut/COMST22_WiFi_Sensing_Survey.pdf).
This paper goes through a survey of many of denoising/feature extraction/dimensionality reduction/etc. techniques and will hopefully give you some ideas!

Closing old issues.
