### ISSUE TITLE
How to flash transmitter when not connected to laptop

### ISSUE THREAD

**Issue by tiyuuu** [StevenMHernandez/ESP32-CSI-Tool#76]
Hi, If I use 2 esp32 , transmitter esp connected with powerbank, and receiver esp connected with laptop, so how can i flash transmitter esp? where will i get the port connection as it is not connected with laptop.
Thanks

**Comment by StevenMHernandez** [comment]
When you flash an ESP32, the firmware is stored on the ESP32 "forever" or until you flash it again. After flashing, you can power the ESP32 from any power source, not just the computer
